# Run at build time (not configure time) so the version stamp embedded
# into the editor reflects the current git state without needing a fresh
# `cmake -B build`. Writes OUTPUT_FILE only when the contents change, so
# unrelated builds don't trigger a relink.

execute_process(
    COMMAND ${GIT_EXECUTABLE} describe --tags --dirty --always
    WORKING_DIRECTORY ${SOURCE_DIR}
    OUTPUT_VARIABLE GIT_DESCRIBE
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)

if(NOT GIT_DESCRIBE)
    set(GIT_DESCRIBE "dev")
endif()

string(REGEX REPLACE "^v" "" DISPLAY_VERSION "${GIT_DESCRIBE}")

set(NEW_CONTENT "// Auto-generated by cmake/GenerateVersion.cmake. Do not edit.\n#pragma once\n#define TIMBRO_DISPLAY_VERSION \"${DISPLAY_VERSION}\"\n")

if(EXISTS ${OUTPUT_FILE})
    file(READ ${OUTPUT_FILE} OLD_CONTENT)
else()
    set(OLD_CONTENT "")
endif()

if(NOT "${OLD_CONTENT}" STREQUAL "${NEW_CONTENT}")
    file(WRITE ${OUTPUT_FILE} "${NEW_CONTENT}")
endif()
